global changes in functions: refusing from verify_args and verify_dependencies (replace to fast and simple code)

diff --git a/examples/session-info b/examples/session-info
--- a/examples/session-info
+++ b/examples/session-info
@@ -26,7 +26,7 @@ Examples: $(basename "$0") "red"
 EOT
   )
   printf "%s\\n" "${msg}"
-}
+  }
 
 #------------------------------------------------------------------------------
 # @function
@@ -35,7 +35,7 @@ EOT
 cleanup() {
   # There's nothing to clean up.
   :
-}
+  }
 
 #------------------------------------------------------------------------------
 # @function
@@ -50,8 +50,8 @@ cleanup() {
 main() {
   # Source the Bash Function Library.
   if ! source "${BASH_FUNCTION_LIBRARY}"; then
-    printf "Error. Unable to source BASH_FUNCTION_LIBRARY.\\n" 1>&2
-    exit 1
+      printf "Error. Unable to source BASH_FUNCTION_LIBRARY.\\n" 1>&2
+      exit 1
   fi
 
   # Display usage message if requested.
@@ -79,27 +79,27 @@ main() {
 
   # Verify argument values.
   case "${color}" in
-    "blue"|"cyan"|"green"|"magenta"|"red"|"yellow"|"white" )
-      name_of_color_constant="bfl_aes_${color}"
-      ;;
-    * )
-      bfl::error "The specified color is not supported." && { usage; exit 1; }
-      ;;
+      "blue"|"cyan"|"green"|"magenta"|"red"|"yellow"|"white" )
+          name_of_color_constant="bfl_aes_${color}"
+          ;;
+      * )
+          bfl::error "The specified color is not supported." && { usage; exit 1; }
+          ;;
   esac
 
   # Get values to display.
   date_now=$(date "+%A, %B %-d, %Y") ||
-    bfl::die "Unable to determine date."
+      bfl::die "Unable to determine date."
   host=$(hostname) ||
-    bfl::die "Unable to determine hostname ."
+      bfl::die "Unable to determine hostname ."
   ip_address_private=$(ip route get 1 | head -n1 | cut -d' ' -f7) ||
-    bfl::die "Unable to determine private IP address."
+      bfl::die "Unable to determine private IP address."
   ip_address_public=$(curl -s --max-time 5 https://ipinfo.io/ip) ||
-    bfl::die "Unable to determine public IP address."
+      bfl::die "Unable to determine public IP address."
   time_now=$(date "+%-l:%M %p %Z") ||
-    bfl::die "Unable to determine time."
+      bfl::die "Unable to determine time."
   user=$(whoami) ||
-    bfl::die "Unable to determine user."
+      bfl::die "Unable to determine user."
 
   # Create border.
   width=$((21+${#date_now}))
@@ -119,7 +119,7 @@ Time:|${time_now}
   "
   printf "%s\\n" "${border}"
   printf "\\n"
-}
+  }
 
 set -euo pipefail
 trap cleanup EXIT
diff --git a/templates/script b/templates/script
--- a/templates/script
+++ b/templates/script
@@ -27,7 +27,7 @@ Example:  $(basename "$0") "Fred" "George" # TODO
 EOT
   )
   printf "%s\\n" "${msg}"
-}
+  }
 
 #------------------------------------------------------------------------------
 # @function
@@ -38,7 +38,7 @@ EOT
 cleanup() {
   # TODO
   :
-}
+  }
 
 #------------------------------------------------------------------------------
 # @function
@@ -54,32 +54,34 @@ cleanup() {
 # shellcheck disable=1090
 #------------------------------------------------------------------------------
 main() {
+  # Verify argument count.
+  [[ $# -eq 2 ]] || { usage; exit 1; }
+  # bfl::verify_arg_count "$#" 2 2 || bfl::die "arguments count $# ≠ 2." ${BFL_ErrCode_Not_verified_args_count}
+
+  # Display usage message if requested.
+# [[ "$#" -gt 0 && 
+  [[               ("$1" = "-h" || "$1" = "--help") ]] && { usage; exit 0; }
+
   # Source the Bash Function Library.
   if ! source "${BASH_FUNCTION_LIBRARY}"; then
     printf "Error. Unable to source BASH_FUNCTION_LIBRARY.\\n" 1>&2
     exit 1
   fi
 
-  # Display usage message if requested.
-  [[ "$#" -gt 0 && ("$1" = "-h" || "$1" = "--help") ]] && { usage; exit 0; }
-
-  # Verify argument count.
-  bfl::verify_arg_count "$#" 2 2 || { usage; exit 1; } # TODO
-
-  # Verify dependencies.
-  bfl::verify_dependencies "printf" # TODO
+  # Verify dependencies.     # TODO
+  [[ ${_BFL_HAS_PRINTF} -eq 1 ]] || bfl::die "dependency 'printf' not found" ${BFL_ErrCode_Not_verified_dependency}
 
   # Declare positional arguments (readonly, sorted by position).
-  declare -r foo="$1" # TODO
-  declare -r bar="$2" # TODO
+  local -r foo="$1" # TODO
+  local -r bar="$2" # TODO
 
   # Declare readonly variables (sorted by name).
-  declare -r wibble="Harry" # TODO
-  declare -r wobble="Ron" # TODO
+  local -r wibble="Harry" # TODO
+  local -r wobble="Ron" # TODO
 
   # Declare all other variables (sorted by name).
-  declare eggs="Dean" # TODO
-  declare ham="Seamus" # TODO
+  local eggs="Dean" # TODO
+  local ham="Seamus" # TODO
 
   # Verify argument values.
   bfl::is_empty "${foo}" && bfl::die "Foo is required." # TODO
@@ -87,7 +89,7 @@ main() {
 
   # TODO
   printf "%s\\n" "${foo}, ${bar}, ${wibble}, ${wobble}, ${eggs}, and ${ham}."
-}
+  }
 
 set -euo pipefail
 trap cleanup EXIT
