bfl::die() => bfl::error

diff --git a/docs/makedoc b/docs/makedoc
--- a/docs/makedoc
+++ b/docs/makedoc
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set +u    # подключаем внешнюю "библиотеку"
+[[ ${_GUARD_BFL_AUTOLOAD} -eq 1 ]] || { . /etc/getConsts || exit 1; . "${BASH_FUNCTIONS_LIBRARY}"; }
 #------------------------------------------------------------------------------
 # @file
 # Creates documentation for library functions.
@@ -7,14 +9,14 @@
 
 #------------------------------------------------------------------------------
 # @function
-# Displays usage message.
+#   Displays usage message.
 #
-# @return string $msg
+# @return String $msg
 #   The usage message.
 #------------------------------------------------------------------------------
 usage() {
-  declare msg
-  msg=$(cat <<EOT
+  local msg
+  msg=$(cat << EOT
 Creates documentation for library functions.
 
 Usage:    $(basename "$0")
@@ -23,125 +25,100 @@ Example:  $(basename "$0")
 EOT
   )
   printf "%s\\n" "${msg}"
-}
+  }
 
 #------------------------------------------------------------------------------
 # @function
-# Main function.
+#   Main function.
 #
 # shellcheck disable=1090
 #------------------------------------------------------------------------------
 main() {
-  # Source the Bash Function Library.
-  if ! source "${BASH_FUNCTION_LIBRARY}"; then
-    printf "Error. Unable to source BASH_FUNCTION_LIBRARY.\\n" 1>&2
-    exit 1
-  fi
-
   # Verify argument count.
-  bfl::verify_arg_count "$#" 0 0 || { usage; exit 1; }
+  [[ $# -eq 0 ]] || { usage; return 1; }
 
   # Verify dependencies.
-  bfl::verify_dependencies "grep" "sed"
+  [[ ${_BFL_HAS_GREP} -eq 1 ]] || { bfl::error "dependency 'grep' not found"; return ${BFL_ErrCode_Not_verified_dependency}; }
+  [[ ${_BFL_HAS_SED} -eq 1 ]]  || { bfl::error "dependency 'sed' not found";  return ${BFL_ErrCode_Not_verified_dependency}; }
 
   # Declare readonly variables (sorted by name).
-  declare -r btx3="\\x60\\x60\\x60" # 3 backticks
-  declare -r header="# Bash Function Library\\n\\n## Function List"
-  declare -r output_file_name="function-list.md"
+  local -r btx3="\\x60\\x60\\x60"   # 3 backticks
+  local -r header="# Bash Function Library\\n\\n## Function List"
+  local -r output_file_name="function-list.md"
 
   # Declare all other variables (sorted by name).
-  declare body
-  declare file
-  declare footer
-  declare func_examples
-  declare func_name
-  declare func_params
-  declare func_returns
-  declare func_summary
-  declare header_examples
-  declare header_params
-  declare header_returns
-
-  declare toc
+  local {body,footer,func_examples,func_name,func_params,func_returns,func_summary,header_examples,header_params,header_returns,toc}=
+  local -i iErr
 
   # Create footer.
   footer="*Last updated: $(date --iso-8601=s).*"
 
-  # Loop through the files.
-  for file in "$(dirname "${BASH_FUNCTION_LIBRARY}")"/_*; do
+  local file   # Loop through the files.
+  for file in "${BASH_FUNCTIONS_LIBRARY%/*}"/*/_*.sh; do
+      # Set the headers for each section. Need to do this each time through the
+      # loop because one or more may be pluralized if there is more than one.
+      header_examples="Example"
+      header_params="Parameter"
+      header_returns="Return"
 
-    # Set the headers for each section. Need to do this each time through the
-    # loop because one or more may be pluralized if there is more than one.
-    header_examples="Example"
-    header_params="Parameter"
-    header_returns="Return"
+      # Find the function name (one line).
+      func_name=$(grep -Eo -m1 "bfl::.+" "${file}" | sed 's/().*//') ||
+        { iErr=$?; bfl::error "Unable to find function name"; return ${iErr}; }
 
-    # Find the function name (one line).
-    func_name=$(grep -Eo -m1 "bfl::.+" "${file}" | sed 's/().*//') \
-      || bfl::die "Unable to find function name"
+      # Find the function description (one entry).
+      func_summary=$(grep -A1 "@function" "${file}" | tail -n1 | sed 's/^# *//') ||
+        { iErr=$?; bfl::error "Unable to find function description."; return ${iErr}; }
 
-    # Find the function description (one entry).
-    func_summary=$(grep -A1 "@function" "${file}" | \
-      tail -n1 | \
-      sed 's/^# *//') \
-      || bfl::die "Unable to find function description."
+      # The sed command to format @param and @return entries:
+      #
+      #   1. Remove leading "#" and spaces from each line.
+      #   2. Add ">" to the beginning of each line.
+      #   3. Replace ">@tag " with a newline.
 
-    # The sed command to format @param and @return entries:
-    #
-    #   1. Remove leading "#" and spaces from each line.
-    #   2. Add ">" to the beginning of each line.
-    #   3. Replace ">@tag " with a newline.
+      # Find the function parameters (zero or more entries).
+      set +e
+      func_params=$(grep -A1 --no-group-separator "# *@param" "${file}" | sed 's/^# *// ; s/^/>/ ; s/>@param /\\n/')
+      [[ "$(grep -c "# *@param" "${file}")" -gt "1" ]] && header_params+="s"
+      set -e
 
-    # Find the function parameters (zero or more entries).
-    set +e
-    func_params=$(grep -A1 --no-group-separator "# *@param" "${file}" | \
-      sed 's/^# *// ; s/^/>/ ; s/>@param /\\n/')
-    [[ "$(grep -c "# *@param" "${file}")" -gt "1" ]] && header_params+="s"
-    set -e
+      # Find the function returns (zero or more entries).
+      set +e
+      func_returns=$(grep -A1 --no-group-separator "# *@return" "${file}" | sed 's/^# *// ; s/^/>/ ; s/>@return /\\n/')
+      [[ "$(grep -c "# *@return" "${file}")" -gt "1" ]] && header_returns+="s"
+      set -e
 
-    # Find the function returns (zero or more entries).
-    set +e
-    func_returns=$(grep -A1 --no-group-separator "# *@return" "${file}" | \
-      sed 's/^# *// ; s/^/>/ ; s/>@return /\\n/')
-    [[ "$(grep -c "# *@return" "${file}")" -gt "1" ]] && header_returns+="s"
-    set -e
+      # The sed command to format @example entries:
+      #
+      #   1. Delete the line containing the @example tag.
+      #   2. Remove leading "#" and spaces from each line.
 
-    # The sed command to format @example entries:
-    #
-    #   1. Delete the line containing the @example tag.
-    #   2. Remove leading "#" and spaces from each line.
+      # Find the function examples (zero or more entries).
+      set +e
+      func_examples=$(grep -A1 --no-group-separator "# *@example" "${file}" | sed '/.*@example.*/d ; s/^# *//' )
+      [[ "$(grep -c "# *@example" "${file}")" -gt "1" ]] && header_examples+="s"
+      set -e
 
-    # Find the function examples (zero or more entries).
-    set +e
-    func_examples=$(grep -A1 --no-group-separator "# *@example" "${file}" | \
-      sed '/.*@example.*/d ; s/^# *//' )
-    [[ "$(grep -c "# *@example" "${file}")" -gt "1" ]] && header_examples+="s"
-    set -e
+      # Surround the examples with 3 backticks.
+      func_examples="\\n${btx3}bash\\n${func_examples}\\n${btx3}\\n"
 
-    # Surround the examples with 3 backticks.
-    func_examples="\\n${btx3}bash\\n${func_examples}\\n${btx3}\\n"
+      # Add to the table of contents.
+      toc+="* [${func_name}](#${func_name//::/})\\n"
 
-    # Add to the table of contents.
-    toc+="* [${func_name}](#${func_name//::/})\\n"
-
-    # Add to the body.
-    body+="## ${func_name}\\n\\n"
-    body+="${func_summary}\\n\\n"
-    ! bfl::is_empty "${func_params}" && body+="**${header_params}**\\n"
-    ! bfl::is_empty "${func_params}" && body+="${func_params}\\n\\n"
-    ! bfl::is_empty "${func_returns}" && body+="**${header_returns}**\\n"
-    ! bfl::is_empty "${func_returns}" && body+="${func_returns}\\n\\n"
-    ! bfl::is_empty "${func_examples}" && body+="**${header_examples}**\\n"
-    ! bfl::is_empty "${func_examples}" && body+="${func_examples}\\n"
+      # Add to the body.
+      body+="## ${func_name}\\n\\n"
+      body+="${func_summary}\\n\\n"
+      bfl::is_empty "${func_params}"   || body+="**${header_params}**\\n"
+      bfl::is_empty "${func_params}"   || body+="${func_params}\\n\\n"
+      bfl::is_empty "${func_returns}"  || body+="**${header_returns}**\\n"
+      bfl::is_empty "${func_returns}"  || body+="${func_returns}\\n\\n"
+      bfl::is_empty "${func_examples}" || body+="**${header_examples}**\\n"
+      bfl::is_empty "${func_examples}" || body+="${func_examples}\\n"
   done
 
-  printf  "%b\\n\\n%b\\n%b---\\n%b\\n" \
-    "${header}" \
-    "${toc}" \
-    "${body}" \
-    "${footer}" \
-    > "$(dirname "${BASH_FUNCTION_LIBRARY}")/docs/${output_file_name}"
-}
+  printf  "%b\\n\\n%b\\n%b---\\n%b\\n" "${header}" "${toc}" "${body}" "${footer}" \
+    > "${BASH_FUNCTIONS_LIBRARY%/*}"/docs/"${output_file_name}"
+
+  }
 
 set -euo pipefail
 main "$@"
diff --git a/examples/session-info b/examples/session-info
--- a/examples/session-info
+++ b/examples/session-info
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set +u    # подключаем внешнюю "библиотеку"
+[[ ${_GUARD_BFL_AUTOLOAD} -eq 1 ]] || { . /etc/getConsts || exit 1; . "${BASH_FUNCTIONS_LIBRARY}"; }
 #------------------------------------------------------------------------------
 # @file
 # Displays a banner with user and system information.
@@ -7,13 +9,13 @@
 
 #------------------------------------------------------------------------------
 # @function
-# Displays usage message.
+#   Displays usage message.
 #
-# @return string $msg
+# @return String $msg
 #   The usage message.
 #------------------------------------------------------------------------------
 usage() {
-  declare msg
+  local msg
   msg=$(cat <<EOT
 Displays a banner with user and system information.
 
@@ -30,7 +32,7 @@ EOT
 
 #------------------------------------------------------------------------------
 # @function
-# Performs cleanup when script exits for any reason. Called by trap.
+#   Performs cleanup when script exits for any reason. Called by trap.
 #------------------------------------------------------------------------------
 cleanup() {
   # There's nothing to clean up.
@@ -39,43 +41,30 @@ cleanup() {
 
 #------------------------------------------------------------------------------
 # @function
-# Main function.
+#   Main function.
 #
-# @param string $color
+# @param String $color
 #   The foreground color of the banner.
 #   Supported colors: blue, cyan, green, magenta, red, yellow, or white.
 #
 # shellcheck disable=1090
 #------------------------------------------------------------------------------
 main() {
-  # Source the Bash Function Library.
-  if ! source "${BASH_FUNCTION_LIBRARY}"; then
-      printf "Error. Unable to source BASH_FUNCTION_LIBRARY.\\n" 1>&2
-      exit 1
-  fi
 
   # Display usage message if requested.
-  [[ "$#" -gt 0 && ("$1" = "-h" || "$1" = "--help") ]] && { usage; exit 0; }
+  [[ "$#" -gt 0 && ("$1" = "-h" || "$1" = "--help") ]] && { usage; return 0; }
 
   # Verify argument count.
-  bfl::verify_arg_count "$#" 0 1 || { usage; exit 1; }
+  (( $#>= 0 && $#<= 1 )) || { usage; return 1; }
 
   # Verify dependencies.
-  bfl::verify_dependencies "curl"
+  [[ ${_BFL_HAS_CURL} -eq 1 ]] || { bfl::error "dependency 'curl' not found"; return ${BFL_ErrCode_Not_verified_dependency}; }
 
   # Declare positional arguments (readonly, sorted by position).
-  declare -r color="${1:-"white"}"
+  local -r color="${1:-"white"}"
 
   # Declare all other variables (sorted by name).
-  declare border
-  declare date_now
-  declare host
-  declare ip_address_private
-  declare ip_address_public
-  declare name_of_color_constant
-  declare time_now
-  declare user
-  declare width
+  local {border,date_now,host,ip_address_private,ip_address_public,name_of_color_constant,time_now,user,width}=
 
   # Verify argument values.
   case "${color}" in
@@ -83,28 +72,24 @@ main() {
           name_of_color_constant="bfl_aes_${color}"
           ;;
       * )
-          bfl::error "The specified color is not supported." && { usage; exit 1; }
-          ;;
+          bfl::error "The specified color is not supported.";
+          usage;
+          return 1 ;;
   esac
 
   # Get values to display.
-  date_now=$(date "+%A, %B %-d, %Y") ||
-      bfl::die "Unable to determine date."
-  host=$(hostname) ||
-      bfl::die "Unable to determine hostname ."
+  date_now=$(date "+%A, %B %-d, %Y") || { iErr=$?; bfl::error "Unable to determine date."; return ${iErr}; }
+  host=$(hostname) || { iErr=$?; bfl::error "Unable to determine hostname ."; return ${iErr}; }
   ip_address_private=$(ip route get 1 | head -n1 | cut -d' ' -f7) ||
-      bfl::die "Unable to determine private IP address."
+    { iErr=$?; bfl::error "Unable to determine private IP address."; return ${iErr}; }
   ip_address_public=$(curl -s --max-time 5 https://ipinfo.io/ip) ||
-      bfl::die "Unable to determine public IP address."
-  time_now=$(date "+%-l:%M %p %Z") ||
-      bfl::die "Unable to determine time."
-  user=$(whoami) ||
-      bfl::die "Unable to determine user."
+    { iErr=$?; bfl::error "Unable to determine public IP address."; return ${iErr}; }
+  time_now=$(date "+%-l:%M %p %Z") || { iErr=$?; bfl::error "Unable to determine time."; return ${iErr}; }
+  user=$(whoami) || { iErr=$?; bfl::error "Unable to determine user."; return ${iErr}; }
 
   # Create border.
   width=$((21+${#date_now}))
-  border=$(bfl::repeat "=" "${width}") ||
-    bfl::die "Unable to create a repeated string."
+  border=$(bfl::repeat "=" "${width}") || { iErr=$?; bfl::error "Unable to create a repeated string."; return ${iErr}; }
 
   # Display the banner.
   printf "%b\\n" "${!name_of_color_constant}"   # Indirect variable expansion.
diff --git a/templates/script b/templates/script
--- a/templates/script
+++ b/templates/script
@@ -11,7 +11,7 @@
 # @function
 # Displays usage message.
 #
-# @return string $msg
+# @return String $msg
 #   The usage message.
 #------------------------------------------------------------------------------
 usage() {
@@ -48,6 +48,7 @@ cleanup() {
 #
 # @param type $foo # TODO
 #   Description. # TODO
+#
 # @param type $bar # TODO
 #   Description. # TODO
 #
@@ -55,21 +56,21 @@ cleanup() {
 #------------------------------------------------------------------------------
 main() {
   # Verify argument count.
-  [[ $# -eq 2 ]] || { usage; exit 1; }
+  [[ $# -eq 2 ]] || { usage; return 1; }
   # bfl::verify_arg_count "$#" 2 2 || bfl::die "arguments count $# ≠ 2." ${BFL_ErrCode_Not_verified_args_count}
 
   # Display usage message if requested.
-# [[ "$#" -gt 0 && 
-  [[               ("$1" = "-h" || "$1" = "--help") ]] && { usage; exit 0; }
+# [[ "$#" -gt 0 &&
+  [[               ("$1" = "-h" || "$1" = "--help") ]] && { usage; return 0; }
 
   # Source the Bash Function Library.
-  if ! source "${BASH_FUNCTION_LIBRARY}"; then
-    printf "Error. Unable to source BASH_FUNCTION_LIBRARY.\\n" 1>&2
-    exit 1
+  if ! source "${BASH_FUNCTIONS_LIBRARY}"; then
+    printf "Error. Unable to source BASH_FUNCTIONS_LIBRARY.\\n" 1>&2
+    return 1
   fi
 
   # Verify dependencies.     # TODO
-  [[ ${_BFL_HAS_PRINTF} -eq 1 ]] || bfl::die "dependency 'printf' not found" ${BFL_ErrCode_Not_verified_dependency}
+  [[ ${_BFL_HAS_PRINTF} -eq 1 ]] || { bfl::error "dependency 'printf' not found"; return ${BFL_ErrCode_Not_verified_dependency}; }
 
   # Declare positional arguments (readonly, sorted by position).
   local -r foo="$1" # TODO
@@ -84,8 +85,8 @@ main() {
   local ham="Seamus" # TODO
 
   # Verify argument values.
-  bfl::is_empty "${foo}" && bfl::die "Foo is required." # TODO
-  bfl::is_empty "${bar}" && bfl::die "Bar is required." # TODO
+  bfl::is_empty "${foo}" && { bfl::error "Foo is required."; return 1; } # TODO
+  bfl::is_empty "${bar}" && { bfl::error "Bar is required."; return 1; } # TODO
 
   # TODO
   printf "%s\\n" "${foo}, ${bar}, ${wibble}, ${wobble}, ${eggs}, and ${ham}."
diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -6,44 +6,47 @@
 #
 #------------------------------------------------------------------------------
 
+set +u    # подключаем внешнюю "библиотеку"
+[[ ${_GUARD_BFL_AUTOLOAD} -eq 1 ]] || { . /etc/getConsts || exit 1; . "${BASH_FUNCTIONS_LIBRARY}"; }
+
 #------------------------------------------------------------------------------
 # @function
-# Tests a function to see if its return code matches the expected return code.
+#   Tests a function to see if its return code matches the expected return code.
 #
-# @param string $function_to_test
+# @param String $function_to_test
 #   The function to be tested.
-# @param string $args
+#
+# @param String $args
 #   The arguments to pass to the function.
-# @param string $expected_return_code
+#
+# @param String $expected_return_code
 #   The expected return code (0 or 1).
 #
 # shellcheck disable=SC2059
 # shellcheck disable=SC2154
 #------------------------------------------------------------------------------
 assert() {
-  bfl::verify_arg_count "$#" 3 3 || exit 1
+  [[ $# -eq 3 ]] || { bfl::error "arguments count $# ≠ 3"; return ${BFL_ErrCode_Not_verified_args_count}; }
 
-  declare -r function_to_test="$1"
-  declare -r args="$2"
-  declare -r expected_return_code="$3"
-  declare actual_return_code
-  declare cmd
-  declare cmd_output
-  declare format
-  declare result
+  local -r function_to_test="$1"
+  local -r args="$2"
+  local -r expected_return_code="$3"
 
   # Test for empty strings.
-  bfl::is_empty "${function_to_test}"     && bfl::die "\$function_to_test is a an empty string."
-  bfl::is_empty "${expected_return_code}" && bfl::die "\$expected_return_code is a an empty string."
+  bfl::is_blank "${function_to_test}"     && { bfl::error "\$function_to_test is required.";     return 1; }
+  bfl::is_blank "${expected_return_code}" && { bfl::error "\$expected_return_code is required."; return 1; }
+
+  local {cmd,cmd_output,format,result}=
+  local -i iErr
 
   # Run the command. The command is run in a subshell (command substitution);
   # exit calls will terminate the subshell, not this script.
   cmd=$(printf "%s %s" "${function_to_test}" "${args}")
   cmd_output=$(eval "${cmd}" 2>&1)
-  actual_return_code="$?"
+  iErr=$?
 
   # Print results.
-  if [[ "${actual_return_code}" -eq "${expected_return_code}" ]]; then
+  if [[ ${iErr} -eq "${expected_return_code}" ]]; then
       result="PASS"
       format="${bfl_aes_green}%-${cw1}s${bfl_aes_reset} %-${cw2}s %-${cw3}s %-${cw4}s %-${cw5}s %-${cw6}s${bfl_aes_reset} \\n"
   else
@@ -51,12 +54,12 @@ assert() {
       format="${bfl_aes_red}%-${cw1}s${bfl_aes_reset} %-${cw2}s %-${cw3}s %-${cw4}s %-${cw5}s %-${cw6}s${bfl_aes_reset} \\n"
   fi
   cmd_output=${cmd_output//[$'\n']}
-  printf "${format}" "${result}" "${function_to_test:0:${cw2}}" "${args:0:${cw3}}" "${expected_return_code}" "${actual_return_code}" "${cmd_output:0:${cw6}}"
+  printf "${format}" "${result}" "${function_to_test:0:${cw2}}" "${args:0:${cw3}}" "${expected_return_code}" "${iErr}" "${cmd_output:0:${cw6}}"
   }
 
 #------------------------------------------------------------------------------
 # @function
-# Main function.
+#   Main function.
 #
 # @param array global $assertions
 #   Global array created by declare_assertions().
@@ -66,24 +69,22 @@ assert() {
 # shellcheck disable=SC2059
 #------------------------------------------------------------------------------
 main() {
-  if ! source "${BASH_FUNCTION_LIBRARY}"; then
-      printf "Error. Unable to source BASH_FUNCTION_LIBRARY.\\n" 1>&2
-      exit 1
-  fi
-
   # Declare column widths (global constants) for displaying test results.
-  declare -rg cw1=6     # Width of column 1: Result (PASS/FAIL)
-  declare -rg cw2=37    # Width of column 2: Function
-  declare -rg cw3=33    # Width of column 3: Arguments
-  declare -rg cw4=8     # Width of column 4: Expected return code
-  declare -rg cw5=6     # Width of column 5: Actual return code
-  declare -rg cw6=109   # Width of column 6: Command output
+  readonly cw1=6     # Width of column 1: Result (PASS/FAIL)
+  readonly cw2=37    # Width of column 2: Function
+  readonly cw3=33    # Width of column 3: Arguments
+  readonly cw4=8     # Width of column 4: Expected return code
+  readonly cw5=6     # Width of column 5: Actual return code
+  readonly cw6=109   # Width of column 6: Command output
+
+# columns width:   Result Function Arguments  returncode    output
+# readonly cw_arr=(   6      37        33       8     6      109 )
+#                 PASS/FAIL                 Expected Actual
 
   # Declare other local variables.
-  declare assertion
-  declare -r format="%-${cw1}s %-${cw2}s %-${cw3}s %-${cw4}s %-${cw5}s %-${cw6}s"
-  declare line_1 line_2 line_3 line_4 line_5 line_6
-  declare -a pieces
+  local -r format="%-${cw1}s %-${cw2}s %-${cw3}s %-${cw4}s %-${cw5}s %-${cw6}s"
+  local {assertion,line_1,line_2,line_3,line_4,line_5,line_6}=
+  local -a pieces
 
   # Create table header lines for for displaying test results.
   line_1=$(bfl::repeat "=" ${cw1})
@@ -102,13 +103,14 @@ main() {
   printf "${format}\\n" "Result" "Function" "Arguments (truncated)" "Code" "Code" "First line of command output (truncated)"
   printf "%s %s %s %s %s %s\\n" "${line_1}" "${line_2}" "${line_3}" "${line_4}" "${line_5}" "${line_6}"
 
-  #
-  for d in lib/*; do
+  for d in "${BASH_FUNCTIONS_LIBRARY%/*}"/lib/*; do
       d="${d##*/}"
-      if [[ -f test/"$d" ]]; then  #  && ! [[ "$d" = 'test' ]]
-          printf "Testing $d library...\n" > /dev/tty
+      if [[ -f "${BASH_FUNCTIONS_LIBRARY%/*}"/test/"$d" ]]; then  #  && ! [[ "$d" = 'test' ]]
+          printf "\n" 2>&1
+          printf "Testing $d library...\n" 2>&1
+          printf "\n" 2>&1
 
-          source test/"$d"
+          source "${BASH_FUNCTIONS_LIBRARY%/*}"/test/"$d"
           declare_assertions # Declare assertions.
 
           # Run assertion tests.
@@ -124,5 +126,5 @@ main() {
   printf "\\n"
   }
 
-set -euo pipefail
+#set -euo pipefail
 main
